### ISSUE TITLE
removed parameter "autocompletion" in click >= 8.1.0 

### ISSUE THREAD

**Issue by petschki** [plone/plonecli#76]
with `click >= 8.1.0` you get the following traceback:

```
Traceback (most recent call last):
  File "/Users/peterm/.pyenv/versions/plone60-py39/bin/plonecli", line 5, in <module>
    from plonecli.cli import cli
  File "/Users/peterm/.pyenv/versions/3.9.11/envs/plone60-py39/lib/python3.9/site-packages/plonecli/cli.py", line 77, in <module>
    def create(context, template, name):
  File "/Users/peterm/.pyenv/versions/3.9.11/envs/plone60-py39/lib/python3.9/site-packages/click/decorators.py", line 287, in decorator
    _param_memo(f, ArgumentClass(param_decls, **attrs))
  File "/Users/peterm/.pyenv/versions/3.9.11/envs/plone60-py39/lib/python3.9/site-packages/click/core.py", line 2947, in __init__
    super().__init__(param_decls, required=required, **attrs)
TypeError: __init__() got an unexpected keyword argument 'autocompletion'
```

pinning `click==8.0.4` in your constraints fixes that

**Comment by petschki** [comment]
ah ... just saw, that the release of `2.2.0` will fix that.

**Comment by jensens** [comment]
run into the same, can we have a release pleae @MrTango ?
